# Generated by Django 5.2.5 on 2026-03-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('type_dni', models.CharField(choices=[('cc', 'Cedula'), ('id', 'Identificacion')], max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('credit_value', models.FloatField()),
                ('interests', models.FloatField()),
                ('months', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'credit',
            },
        ),
    ]
